import type { Metadata } from "next";
import "./globals.scss";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeProviderCustom from "../providers/ThemeProvider";
import 'dayjs/locale/es';
import dayjs from "dayjs";
import { CustomProvider } from 'rsuite';
dayjs.locale('es');
import 'rsuite/dist/rsuite-no-reset.min.css';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import esAR from 'rsuite/locales/es_AR';


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" >
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderCustom>
            <CustomProvider locale={esAR}>{children}</CustomProvider>
          </ThemeProviderCustom>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
