import type { Metadata } from "next";
import "./globals.scss";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeProviderCustom from "../providers/ThemeProvider";
import 'dayjs/locale/es';
import dayjs from "dayjs";
dayjs.locale('es');
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" >
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderCustom>
            {children}
          </ThemeProviderCustom>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
