import type { Metadata } from "next";
import "./globals.scss";
import { Open_Sans } from 'next/font/google';
const openSans = Open_Sans({ subsets: ['latin'], display: 'swap' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={openSans.className}>
      <body>{children}</body>
    </html>
  );
}
